// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grtanmuzjwmuayhljoqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdydGFubXV6andtdWF5aGxqb3FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0ODM2MzIsImV4cCI6MjA3NDA1OTYzMn0.tQuT7by7aDyw5fcvoufU9jaEZkfH6bbHzmAxwKw5Ym8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});